
version: '2.0'

services:
  database:
    image: mongo:4.4.26
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

  mongoexpress:
    image: mongo-express:1.0-18
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_DB_PASSWORD}
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:1998
    env_file:
      - .env
    environment:
      - MONGO_USER=${MONGO_DB_USERNAME}
      - MONGO_PASS=${MONGO_DB_PASSWORD}
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_NAME=${MONGO_DB_NAME}
    
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    environment:
      - MONGO_USER=${MONGO_DB_USERNAME}
      - MONGO_PASS=${MONGO_DB_PASSWORD}
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_NAME=${MONGO_DB_NAME}
